name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test

      - name: Generate Mochawesome report
        run: npm run generate:report

      - name: List reports directory
        if: always()
        run: ls -l cypress/reports

      - name: Find latest Mochawesome HTML report
        id: find_report
        run: |
          latest=$(ls -t cypress/reports/index*.html | head -n 1)
          echo "latest_report=$latest" >> $GITHUB_OUTPUT

      - name: Upload latest Mochawesome HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ${{ steps.find_report.outputs.latest_report }}

      - name: List all files in cypress/reports
        run: ls -l cypress/reports

      - name: Upload Cypress videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Add Mochawesome report info to summary
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            core.summary
              .addHeading('Test Artifacts')
              .addLink('Download Mochawesome HTML Report (artifact)', 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}')
              .addRaw('After the run completes, scroll down to the Artifacts section and download <b>index.html</b> (or similar) from <b>mochawesome-report</b>.')
              .write()
